GEE/GEE/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('authentification.urls')),
    path('app/', include('app.urls')),
    path('forum/', include('forum.urls')),
]

handler400 = 'errorPages.views.error_400_view'
handler403 = 'errorPages.views.error_403_view'
handler404 = 'errorPages.views.error_404_view'
handler500 = 'errorPages.views.error_500_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GEE/TFC/TFC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authe.urls')),
    path('/forum/',include('forum.urls')),
    path('erroPages',include('errorPages.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

GEE/app/urls.py
from django.urls import path
from .views import UpdateApp,Logo, CreateStudent,Palmares,AppartClasseStudent,PasseCreate,Edition,CoursCreate,ListeEleveEnsPalma,EpreuveCreate,OptionCreate,Search,EleveUpdateviews, DeleteEleve,ClassCreate
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = "app"
urlpatterns = [
    path('logo', Logo, name="logo"),
    path('updateApp', UpdateApp, name="updateApp"),
    path('createStudent', CreateStudent.as_view() , name="create_student"),
    path('appartclasse', AppartClasseStudent.as_view(), name="appartclasse"),
    path('listeleve', ListeEleveEnsPalma, name="liste_eleve") ,
    path('searchStudent', Search, name="searchStudent"),
    path('update_eleve/<int:pk>', EleveUpdateviews.as_view(), name='eleve_update'),
    path('delete_eleve/<int:id>', DeleteEleve, name='suppression'),
    ##-----------CLASSE-----------
    path('classecreate', ClassCreate.as_view() , name="create_classe"),
    ##-----------OPTION-----------
    path('Creationoption', OptionCreate.as_view() , name="create_option"),
    ##-----------EPREUVE-----------
    path('epreuvecreate', EpreuveCreate.as_view() , name="create_epreuve"),
    ##-----------COURS-----------
    path('courscreate', CoursCreate.as_view() , name="create_cours"),
     ##-----------PASSER-----------
    path('passecreate', PasseCreate.as_view() , name="create_passe"),
     ##-----------EDITION-----------
    path('edition', Edition , name="edition_liste"),
     ##-----------PROCLAMATION-----------
    path('proclamation', Palmares , name="proclamation"),
]

urlpatterns += staticfiles_urlpatterns()

GEE/app/models.py
from django.db import models

# Create your models here.
class Classe(models.Model):
    code_class = models.CharField("Code-Classe", max_length=50, blank=False)
    lib_class = models.CharField("Libellé-Classe", max_length=20, null=False)
    
    
    class Meta():
        verbose_name = ('Classe')
        verbose_name_plural = ('Classes')
        
    def __str__(self) -> str:
        return self.lib_class

class Option(models.Model):
    code_opt = models.CharField("Code-Option", max_length=50, blank=False)
    lib_opt = models.CharField("Libellé-Option", max_length=20, null=False)
    
    def __str__(self) -> str:
        return self.lib_opt
    
class Eleve(models.Model):
    matr_eleve = models.CharField("Matricule", blank=False,max_length=30)
    nom_el = models.CharField("Nom-Elève", max_length=30, null=False)
    post_nom_el = models.CharField("Post-Nom-Elève", max_length=30, null=False,default="")
    prenom_el = models.CharField("Prenom-Elève", max_length=30, null=False,default="")
    date_nais_el = models.CharField("Date-naissance-Elève", max_length=30, null=False,default="")
    sexe_el = models.CharField("Sexe Elève", max_length=1, null=False, default="M")
    nom_titeur = models.CharField("Nom-Titeur", max_length=30, null=False,default="")
    classe = models.ForeignKey(Classe,  on_delete=models.CASCADE, default=1)
    option = models.ForeignKey(Option, on_delete=models.CASCADE, default=1)
    Adress_el = models.CharField("Adresse-Elève", max_length=30, default="")
    Tel_titeur = models.CharField("Numéro-tuteur", max_length=30, null=False,default="")
    
    def __str__(self) -> str:
        return self.nom_el
    
class Enseigant(models.Model):
    nom_ens =  models.CharField("Nom-Enseignant", max_length=30, null=False)
    matr_ens = models.CharField("Matricule-Enseignant", blank=False,max_length=30)
    post_ens = models.CharField("Post-Nom-Enseigant", max_length=30, null=False,default="")
    prenom_ens = models.CharField("Prenom-Enseigant", max_length=30, null=False,default="")
    date_nais_ens = models.CharField("Date-Naissance-Enseigant", max_length=30, null=False,default="")
    sexe_ens = models.CharField("Sexe", max_length=1, null=False, default="M")
    etat_civil_ens = models.CharField("Etat-Civil", max_length=1, null=False, default="C")
    niveau_etude =models.CharField("Niveau-D'étude",max_length=30, null=False)
    adresse_ens = models.CharField("Adresse-Enseignant", max_length=30, default="")
    date_engagement = models.CharField("Date-Engagement", max_length=30, null=False,default="")
    tel_ens = models.CharField("Numéro-Enseigant", max_length=30, null=False,default="")
    
    
    def __str__(self) -> str:
        return self.nom_ens
    
class Cours(models.Model):
    code_cours =  models.CharField("Code-Cours", blank=False,max_length=30)
    lib_cours =  models.CharField("Nom-Cours", blank=False,max_length=100)
    Ponderation = models.IntegerField("Pondération", blank=False)
    
    class Meta:
        verbose_name = ("Cours")
        verbose_name_plural = ("Cours")
    
    
    def __str__(self) -> str:
        return self.lib_cours
    
class Epreuve(models.Model):
    code_epr = models.CharField("Code-Epreuve", blank=False, max_length=4)
    Lib_epr = models.CharField("Libéllé-Epreuve", blank=False,max_length=40)
    max_epr = models.CharField("Max-Epreuve",blank=True,max_length=3)
    
     
    def __str__(self) -> str:
        return self.Lib_epr

class Appartenir(models.Model):
    anne_scol = models.CharField("Anne-Scolaire", max_length=30, null=False)
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    
     
    def __str__(self) -> str:
        return self.eleve.nom_el

class Periode(models.Model):
    code_per = models.CharField("Code-Période", blank=False,max_length=30)
    lib_periode = models.CharField("Libéllé-Période", blank=False,max_length=50)
    
    
    def __str__(self) -> str:
        return self.lib_periode

class Semestre(models.Model):
    code_sem = models.CharField("Code-Semestre", blank=False,max_length=30)
    lib_sem = models.CharField("Libéllé-Semestre", blank=False,max_length=50)
    
    
    def __str__(self) -> str:
        return self.lib_sem
    
class Passer(models.Model):
    eleve_pas = models.ForeignKey(Eleve, on_delete=models.CASCADE,verbose_name="Eleve")
    epreuve_pas = models.ForeignKey(Epreuve, on_delete=models.CASCADE,verbose_name="Epreuve")
    cours_pas = models.ForeignKey(Cours, on_delete=models.CASCADE,verbose_name="Cours")
    date_pass = models.CharField("Date", max_length=30, blank=False)
    point_obt =models.IntegerField("Point-Obtenu",  blank=False)
   #max_cours = models.IntegerField("Maximum-Epreuve", blank=False)
    periode =  models.ForeignKey(Periode, on_delete=models.CASCADE,verbose_name="Période")
    semestre =  models.ForeignKey(Semestre, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.eleve_pas.nom_el
    
class Dispenser(models.Model):
    classe_disp = models.ForeignKey(Classe, on_delete=models.CASCADE)
    cours_disp = models.ForeignKey(Cours, on_delete=models.CASCADE)
    enseigant_disp = models.ForeignKey(Enseigant, on_delete=models.CASCADE)
    anne_scol_disp =  models.CharField("Année-Scolaire", max_length=30, blank=False)
    
    def __str__(self) -> str:
        return self.classe_disp.lib_class

class Titulaire(models.Model):
    enseigant_titulaire = models.ForeignKey(Enseigant, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    anne_scol =  models.CharField("Année-Scolaire", max_length=30, blank=False)
    
    def __str__(self) -> str:
        return self.enseigant_titulaire.nom_ens

GEE/app/forms.py
from .models import *
from django import forms
from .models import Classe
from django.contrib.admin.widgets import FilteredSelectMultiple

#------------ELEVE------------------
class EleveForm(forms.ModelForm):
      sexe_choice = (
          ("M", "MASCULIN"),
          ("F", "FEMININ")
      )
      matr_eleve = forms.CharField(label='Matricule Elève', widget=forms.TextInput(
            attrs={
              'class': 'form-control ',
            }), required=True)
      nom_el = forms.CharField(label='nom', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      post_nom_el = forms.CharField(label='Post-Nom', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      prenom_el = forms.CharField(label='Prenom', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      date_nais_el = forms.CharField(label='Date-naissance', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
              'type': 'Date',
            }), required=True)
      sexe_el = forms.ChoiceField( widget=forms.Select(
            attrs={
              'class': 'form-control    my-2',
            }), choices=sexe_choice )
      nom_titeur = forms.CharField(label='Nom-Titeur', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      classe = forms.Select()
      Adress_el = forms.CharField(label='Adresse', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }))
      Tel_titeur = forms.CharField(label='Numéro-Titeur', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      
      
      class Meta:
            model = Eleve
            fields = '__all__'

#----------------------APPARTENIR--------------------------
class AppartClassForm(forms.ModelForm):
     
      anne_scol = forms.CharField(label='Année-Scolaire', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      
      class Meta:
            model = Appartenir
            fields = '__all__'
            
#------------------------CLASSE--------------------------
class ClassCreateForm(forms.ModelForm):
      code_class = forms.CharField(label='Code-classe', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      lib_class = forms.CharField(label='Libellé-classe', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      class Meta:
            model = Classe
            fields = '__all__'
            
#------------------------OPTION--------------------------
class OptionCreateForm(forms.ModelForm):
      code_opt = forms.CharField(label='Code-option', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      lib_opt = forms.CharField(label='Libellé-option', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      class Meta:
            model = Option
            fields = '__all__'

            
#------------------------EPREUVE--------------------------
class EpreuveCreateForm(forms.ModelForm):
      code_epr = forms.CharField(label='Code-épreuve', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      Lib_epr = forms.CharField(label='libellé-épreuve', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      max_epr = forms.CharField(label='Max', widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      
      
      class Meta:
            model = Epreuve
            fields = '__all__'
            
#------------------------COURS--------------------------
class CoursCreateForm(forms.ModelForm):
      code_cours =  forms.CharField(label="Code-Cours", widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      lib_cours =  forms.CharField(label="Nom-Cours", widget=forms.TextInput(
            attrs={
              'class': 'form-control',
            }), required=True)
      Ponderation = forms.IntegerField(label="Pondération", widget=forms.TextInput(
            attrs={
              'class': 'form-control',
              'type': 'number',
            }), required=True)
      
      class Meta:
            model = Cours
            fields = '__all__'

class PasserCreateForm(forms.ModelForm):
    eleve_pas = forms.Select()
    epreuve_pas = forms.Select()
    cours_pas = forms.Select()
    date_pass = forms.CharField(label="Date",  widget=forms.TextInput(
            attrs={
              'class': 'form-control',
              'type': 'date',
              
            }), required=True)
    point_obt =forms.IntegerField(label="Point-Obtenu",  widget=forms.TextInput(
            attrs={
              'class': 'form-control',
              'type': 'number',
            }), required=True)
    periode =  forms.Select()
    semestre =  forms.Select()
      
    class Meta:
            model = Passer
            fields = '__all__'

GEE/app/templates/create-cours.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        CREATION COURS
       </h1>
       <P>Vous pouvez créer un cours</p>
    </div>
</div>

<form method="POST" enctype="multipart/form-data" class="bg-ligth shadow-lg forms-disc space   p-4 ">  
    {% csrf_token %}
    <div class=" text-center">
        {% if messages  %}
        <div class="alert alert-success text-center">
          {{ messages }}
        </div>
        {% endif%}
    </div>
   <div class="form-group ">
    {{ form.as_p }}
   </div>
   <button type="submit " class="btn btn-primary text-white">Créer</button>
</form>
{% endblock %}

{%block style%}
<style type="text/css">
.space{
    margin: 3% auto;
}
</style>
{%endblock%}
{% block footer %}
<script type="text/javascript">
    select_input = document.querySelector("#id_classe")
    option_input = document.querySelector("#id_option")
 

    select_input.classList.add("form-select")
    option_input.classList.add("form-select")
  
</script>
{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/create-passe.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        CREATION PASSATION EPREUVE 
       </h1>
       <P>Vous pouvez créer une épreuve a passer</p>
    </div>
</div>

<form method="POST" enctype="multipart/form-data" class="bg-ligth shadow-lg forms-disc space   p-4 ">  
    {% csrf_token %}
    <div class=" text-center">
        {% if messages  %}
        <div class="alert alert-success text-center">
          {{ messages }}
        </div>
        {% endif%}
    </div>
   <div class="form-group text-dark">
    {{ form.as_p }}
   </div>
   <button type="submit " class="btn btn-primary text-white">Créer</button>
</form>
{% endblock %}

{%block style%}
<style type="text/css">
.space{
    margin: 3% auto;
}
</style>
{%endblock%}
{% block footer %}
<script type="text/javascript">
    select_input1 = document.querySelector("#id_eleve_pas")
    select_input2 = document.querySelector("#id_epreuve_pas")
    select_input3 = document.querySelector("#id_cours_pas")
    select_input4 = document.querySelector("#id_periode")
    select_input5 = document.querySelector("#id_semestre")
    input_date = document.querySelector("#id_date_pass")
    
    select_input1.classList.add("form-select")
    select_input2.classList.add("form-select")
    select_input3.classList.add("form-select")
    select_input4.classList.add("form-select")
    select_input5.classList.add("form-select")
    
</script>
{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/create-student.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        CREATION ELEVE
       </h1>
       <P>Vous pouvez Enregistrer un élève</p>
    </div>
</div>

<form method="POST" enctype="multipart/form-data" class="bg-ligth shadow-lg forms-disc space   p-4 ">  
    {% csrf_token %}

   </H3>
   <div class="form-group ">
    {{ form.as_p }}
   </div>
   <button type="submit " class="btn btn-primary text-white">Créer</button>
</form>
{% endblock %}

{%block style%}
<style type="text/css">
.space{
    margin: 3% auto;
}
</style>
{%endblock%}
{% block footer %}
<script type="text/javascript">
    select_input = document.querySelector("#id_classe")
    option_input = document.querySelector("#id_option")
 

    select_input.classList.add("form-select")
    option_input.classList.add("form-select")
  
</script>

{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/edition.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        EDITIONS DE DONNEES
       </h1>
       <P>Vous pouvez éditer une liste des données</p>
    </div>
</div>
{% endblock %}

{% block section %}
<section class="my-5  ">
    <div class="container my-5">
        <!-- ============================================================== -->
        <!-- Three charts -->
        <!-- ============================================================== -->
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title">
                        <a href="{% url 'app:liste_eleve'%}?page=impression_liste&imprimer=student" class="ms-auto" > 
                        LISTE DES ELEVE </a></h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                          <div id="sparklinedash"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                          <a href="{% url 'app:liste_eleve'%}?page=impression_liste&imprimer=student" class="ms-auto" > <li class="ms-auto"><span class="counter text-success"><i class=" fa fa-bullhorn text-primary" ></i></span></li></a>
                      </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title text-primary"><a href="{% url 'app:liste_eleve'%}?page=impression_liste&imprimer=teacher" class="ms-auto" > 
                        LISTE DES ENSEIGNANT</a></h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash2"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                        <li class="ms-auto"><span class="counter text-purple"><a href="{% url 'app:liste_eleve'%}?page=impression_liste&imprimer=teacher" class="ms-auto" > 
                            <i class=" fa fa-users text-primary" ></i></a > </span></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title text-primary">PALMARES DE REUSSITE</h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash3"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                        <li class="ms-auto"><span class="counter text-primary"><i class=" fa fa-child text-primary" ></i>
                        </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock%}

{%block style%}
<style type="text/css">
.space{
    margin: 3% auto;
}
</style>
{%endblock%}
{% block footer %}
<script type="text/javascript">
  
</script>
{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/eleve_delete.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        SUPPRESION ELEVE
       </h1>
       <P>Vous pouvez supprimé un élève dans la base des données</p>
    </div>
</div>

<form method="POST" enctype="multipart/form-data" class="bg-ligth shadow-lg forms-disc space   p-4 ">  
    {% csrf_token %}

   <div class="form-group ">
    {{ form.as_p }}
   </div>
   <button type="submit " class="btn btn-primary text-white">Envoyer</button>
</form>
{% endblock %}


{% block footer %}
<script type="text/javascript">
    select_input = document.querySelector("#id_classe")
    option_input = document.querySelector("#id_option")
 

    select_input.classList.add("form-select")
    option_input.classList.add("form-select")
  
</script>
{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/liste_eleve.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
        LISTE DES ELEVES
       </h1>
       <P>Vous avez la possibilité de voir la liste des élèves et de modifier les informations qui leur sont attachée</p>
    </div>
</div>

<form method="get" action="{% url 'app:searchStudent' %}" enctype="multipart/form-data" class="container my-3 ">  
<div class="container ">
  <div class="form-group ">
    <input type="text" class="form-control shadow-sm py-3" id="search" name="search" placeholder="Enter your search" /><br>
    <button type="submit " class="btn btn-primary text-white">Rechercher</button>
  </div>
  <div> </div>
</div>
</form>
<table class="table container shadow-lg  my-5">
    <thead>
      <tr>
        <th scope="col">Matricule</th>
        <th scope="col">Nom</th>
        <th scope="col">Post-Nom</th>
        <th scope="col">Classe</th>
        <th scope="col">Option</th>
        <th scope="col">Suppression</th>
        <th scope="col">Modification</th>
      </tr>
    </thead>
    <tbody>
        {% for instance in Eleve %}
        <tr>
            <th scope="row">{{ instance.matr_eleve}}</th>
            <td>{{ instance.nom_el }}</td>
            <td>{{ instance.post_nom_el}}</td>
            <td>{{ instance.classe }}</td>
            <td>{{ instance.option }}</td>
           <td><a href="{% url 'app:suppression' instance.id %}" class="btn btn-danger text-white delete">Supprimer<a></td>
           <td><a href="{% url 'app:eleve_update' instance.id %}" class="btn btn-primary update">Modifier<a></td>
          </tr>
       {% endfor %}
      
    </tbody>
  </table><br>
  
{% endblock %}

{% block footer %}
{% include 'layout/partials/footer.html'%}
{% endblock %}

GEE/app/templates/logo.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% endblock %}
{% block content %}
<div class="logo">
    <img src="{% static 'picture/Gee.App.jpg' %}" alt="Logo">
<div>
{% endblock %}

GEE/app/templates/mise_ajour.html
{%extends 'layout/base.html'%}
{% block nav%}
{% include 'layout/partials/nav.html'%}
{% endblock %}
{% block content %}
<div class=" home bg-primary">
    <div class="mt-5 p-4 text-white text-center">
       <h1 class="display-4 " >
           MISE AJOUR
       </h1>
       <p className="lead"> Vous pouvez mettre à jour les tables si dessous </p>
       <hr className="my-4"></hr>
</div>
</div>
{% endblock %}


{% block section %}
<div class="container mt-4 marge">
    <div class="row">
        <div class="col-sm-4 shadow-lg">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title fw-bold">ELEVE</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'app:create_student' %}" class="btn btn-outline-primary shadow-lg   my-2">Création</a>
              <a href="{% url 'app:liste_eleve' %}?page=UpdateAndDelete" class=" btn btn-primary shadow-lg mx-1">Modification</a>
            </div>
          </div>
        </div>
        <div class="col-sm-4 shadow-lg">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title fw-bold">CLASSE</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'app:create_classe' %}" class="btn btn-primary shadow-lg   text-white">Création</a>
            </div>
          </div>
        </div>
        <div class="col-sm-4 shadow-lg">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title fw-bold">OPTION</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="{% url 'app:create_option' %}" class="btn btn-outline-primary shadow-lg ">Création</a>
              </div>
            </div>
          </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-4 shadow-lg">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title fw-bold">COURS</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'app:create_cours' %}" class="btn btn-primary shadow-lg ">Création</a>
              
            </div>
          </div>
        </div>
        <div class="col-sm-4 shadow-lg">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title fw-bold">EPREUVE</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{% url 'app:create_epreuve' %}" class="btn btn-primary shadow-lg   text-white">Création</a>
            </div>
          </div>
        </div>
        <div class="col-sm-4 shadow-lg ">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title fw-bold">PASSER</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="{% url 'app:create_passe' %}" class="btn btn-primary shadow-lg   ">Création</a>
              </div>
            </div>
          </div>
      </div>
      
</div>
{% endblock%}

{% block footer %}
{% include 'layout/partials/footer.html'%}
{% endblock %}