GEE/GEE/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('authentification.urls')),
    path('app/', include('app.urls')),
    path('forum/', include('forum.urls')),
]

handler400 = 'errorPages.views.error_400_view'
handler403 = 'errorPages.views.error_403_view'
handler404 = 'errorPages.views.error_404_view'
handler500 = 'errorPages.views.error_500_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GEE/TFC/TFC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authe.urls')),
    path('/forum/',include('forum.urls')),
    path('erroPages',include('errorPages.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

GEE/app/urls.py
from django.urls import path
from .views import UpdateApp,Logo, CreateStudent,Palmares,AppartClasseStudent,PasseCreate,Edition,CoursCreate,ListeEleveEnsPalma,EpreuveCreate,OptionCreate,Search,EleveUpdateviews, DeleteEleve,ClassCreate
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = "app"
urlpatterns = [
    path('logo', Logo, name="logo"),
    path('updateApp', UpdateApp, name="updateApp"),
    path('createStudent', CreateStudent.as_view() , name="create_student"),
    path('appartclasse', AppartClasseStudent.as_view(), name="appartclasse"),
    path('listeleve', ListeEleveEnsPalma, name="liste_eleve") ,
    path('searchStudent', Search, name="searchStudent"),
    path('update_eleve/<int:pk>', EleveUpdateviews.as_view(), name='eleve_update'),
    path('delete_eleve/<int:id>', DeleteEleve, name='suppression'),
    ##-----------CLASSE-----------
    path('classecreate', ClassCreate.as_view() , name="create_classe"),
    ##-----------OPTION-----------
    path('Creationoption', OptionCreate.as_view() , name="create_option"),
    ##-----------EPREUVE-----------
    path('epreuvecreate', EpreuveCreate.as_view() , name="create_epreuve"),
    ##-----------COURS-----------
    path('courscreate', CoursCreate.as_view() , name="create_cours"),
     ##-----------PASSER-----------
    path('passecreate', PasseCreate.as_view() , name="create_passe"),
     ##-----------EDITION-----------
    path('edition', Edition , name="edition_liste"),
     ##-----------PROCLAMATION-----------
    path('proclamation', Palmares , name="proclamation"),
]

urlpatterns += staticfiles_urlpatterns()

GEE/authentification/urls.py
from django.urls import path
from .views import Login,Register,Home,deconnexion,update_profile 
app_name = 'accounts'

urlpatterns = [
    path('', Login, name='Login'),
    path('register', Register, name='Register'),
    path('logout', deconnexion, name='Logout'),
    path('home', Home, name='Home'),
    path('profile/<int:id>', update_profile, name='update_profile'),
    #path('update/<int:pk>/profile',  UpdateProfile.as_view(), name='update_profile')
]

GEE/forum/urls.py
from django.urls import path
from .views import Communication,DiscutionFunc

app_name = "forum"

urlpatterns = [
    path('communiquer/', Communication,name="communiquer"),
    path('discussion', DiscutionFunc, name="discussion"),
    #path('error404',error_http_404_views, name='error_404')
    
]

GEE/templates/layout/partials/footer.html
{%extends 'layout/base.html'%}
{% block nav%}
{% endblock %}

{% block content %}
{% endblock %}
{% block footer %}
<div class="bg-primary position-fixed bottom-0 start-0 end-0 shadow-lg ">
    <footer>
        <div class="text-center display">
               <div>
                <i class="fa fa-home"></i><br>
                <a href="{% url 'accounts:Home' %}" class="text-light">Home</a>
               </div>
               {% if request.user.is_staff %}
               <div>
                <i class="fa fa-cogs"></i><br>
                <a href="{% url 'admin:index' %}" class="text-light">Parametre</a>
                </div>
                {% endif %}
               <div>
                <i class="fa fa-user"></i><br>
                <a href="{% url 'accounts:update_profile' request.user.id %}" class="text-light">Profile</a>
                </div>
        </div>
    </footer>
</div>
{% endblock %}

GEE/templates/layout/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-light  bg-primary  position-fixed  start-0 end-0 top-0 ">
    <div class="container-fluid">
      <span class="navbar-brand" href="#">GEE.App</span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav text-white">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href="{% url 'accounts:Home' %}">Home</a>
          </li>
          
         {% if request.user.is_staff %}
         <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'app:edition_liste' %}">Edition</a>
        </li>
         {% endif %}
        {%if update %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'app:updateApp'%}">{{update }}</a>
        </li>
        {% endif %}
         
         <li class="nav-item">
          <a class="nav-link text-white" href="#">A propos</a>
        </li>
          <li class="nav-item">
            <a class="nav-link btn text-white " href="{% url 'accounts:Logout' %}"  tabindex="-1" aria-disabled="true">Déconnexion</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

GEE/templates/layout/partials/section.html
{%extends 'layout/base.html'%}
{% load  static  %}
{% block nav%}
{% endblock %}

{% block  head %}
<link href="{% static 'css2/style.min.css' %}" rel="stylesheet">
{% block lien %}
   <link rel="stylesheet" type="text/css" href="{% static '/boostrap/css/bootstrap.min.css' %}"> 
 {%  endblock%} 
{% endblock %}
{% block content %}
{% endblock %}

{% block section %}
<section class=" my-5">
    <div class="container">
        <!-- ============================================================== -->
        <!-- Three charts -->
        <!-- ============================================================== -->
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title">
                        <a href="{% url 'forum:communiquer'%}" class="ms-auto" > 
                        COMMUNIQUER </a></h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                          <div id="sparklinedash"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                          <a href="{% url 'forum:communiquer'%}" class="ms-auto" > <li class="ms-auto"><span class="counter text-success"><i class=" fa fa-bullhorn text-primary" ></i></span></li></a>
                      </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title text-primary"><a href="{% url 'forum:discussion'%}" class="ms-auto" > 
                        DISCUSSION</a></h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash2"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                        <li class="ms-auto"><span class="counter text-purple"><a href="{% url 'forum:communiquer'%}" class="ms-auto" > 
                            <i class=" fa fa-users text-primary" ></i></a > </span></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="white-box analytics-info shadow-lg">
                    <h3 class="box-title text-primary"><a href="{% url 'app:proclamation'%}" class="ms-auto" >PROCLAMATION</a></h3>
                    <ul class="list-inline two-part d-flex align-items-center mb-0">
                        <li>
                            <div id="sparklinedash3"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas></div>
                        </li>
                        <li class="ms-auto"><span class="counter text-primary"><a href="{% url 'app:proclamation'%}" class="ms-auto" ><i class=" fa fa-child text-primary" ></i></a>
                        </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock%}

{% block footer %}
{% endblock %}